// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  GR1DRestartHDF5PluginInfo.h
// ****************************************************************************

#ifndef GR1DRESTARTHDF5_PLUGIN_INFO_H
#define GR1DRESTARTHDF5_PLUGIN_INFO_H
#include <DatabasePluginInfo.h>
#include <database_plugin_exports.h>

class avtDatabase;
class avtDatabaseWriter;

// ****************************************************************************
//  Class: GR1DRestartHDF5DatabasePluginInfo
//
//  Purpose:
//    Classes that provide all the information about the GR1DRestartHDF5 plugin.
//    Portions are separated into pieces relevant to the appropriate
//    components of VisIt.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
//  Modifications:
//
// ****************************************************************************

class GR1DRestartHDF5GeneralPluginInfo : public virtual GeneralDatabasePluginInfo
{
  public:
    virtual const char *GetName() const;
    virtual const char *GetVersion() const;
    virtual const char *GetID() const;
    virtual bool  EnabledByDefault() const;
    virtual bool  HasWriter() const;
    virtual std::vector<std::string> GetDefaultFilePatterns() const;
    virtual bool  AreDefaultFilePatternsStrict() const;
    virtual bool  OpensWholeDirectory() const;
};

class GR1DRestartHDF5CommonPluginInfo : public virtual CommonDatabasePluginInfo, public virtual GR1DRestartHDF5GeneralPluginInfo
{
  public:
    virtual DatabaseType              GetDatabaseType();
    virtual avtDatabase              *SetupDatabase(const char * const *list,
                                                    int nList, int nBlock);
};

class GR1DRestartHDF5MDServerPluginInfo : public virtual MDServerDatabasePluginInfo, public virtual GR1DRestartHDF5CommonPluginInfo
{
  public:
    // this makes compilers happy... remove if we ever have functions here
    virtual void dummy();
};

class GR1DRestartHDF5EnginePluginInfo : public virtual EngineDatabasePluginInfo, public virtual GR1DRestartHDF5CommonPluginInfo
{
  public:
    virtual avtDatabaseWriter        *GetWriter(void);
};

#endif
