// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: GR1DRestartHDF5PluginInfo.C
// ****************************************************************************

#include <GR1DRestartHDF5PluginInfo.h>

#include <visit-config.h>
VISIT_PLUGIN_VERSION(GR1DRestartHDF5,DBP_EXPORT)

VISIT_DATABASE_PLUGIN_ENTRY(GR1DRestartHDF5,General)

// ****************************************************************************
//  Method: GR1DRestartHDF5GeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
GR1DRestartHDF5GeneralPluginInfo::GetName() const
{
    return "GR1DRestartHDF5";
}

// ****************************************************************************
//  Method: GR1DRestartHDF5GeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
GR1DRestartHDF5GeneralPluginInfo::GetVersion() const
{
    return "1.0";
}

// ****************************************************************************
//  Method: GR1DRestartHDF5GeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
GR1DRestartHDF5GeneralPluginInfo::GetID() const
{
    return "GR1DRestartHDF5_1.0";
}
// ****************************************************************************
//  Method: GR1DRestartHDF5GeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
GR1DRestartHDF5GeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
// ****************************************************************************
//  Method: GR1DRestartHDF5GeneralPluginInfo::HasWriter
//
//  Purpose:
//    Return true if this plugin has a database writer.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
GR1DRestartHDF5GeneralPluginInfo::HasWriter() const
{
    return false;
}
// ****************************************************************************
//  Method:  GR1DRestartHDF5GeneralPluginInfo::GetDefaultFilePatterns
//
//  Purpose:
//    Returns the default patterns for a GR1DRestartHDF5 database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
std::vector<std::string>
GR1DRestartHDF5GeneralPluginInfo::GetDefaultFilePatterns() const
{
    std::vector<std::string> defaultPatterns;
    defaultPatterns.push_back("restart_nt_*_time_*.h5");
    defaultPatterns.push_back("restart_*.h5");

    return defaultPatterns;
}

// ****************************************************************************
//  Method:  GR1DRestartHDF5GeneralPluginInfo::AreDefaultFilePatternsStrict
//
//  Purpose:
//    Returns if the file patterns for a GR1DRestartHDF5 database are
//    intended to be interpreted strictly by default.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
GR1DRestartHDF5GeneralPluginInfo::AreDefaultFilePatternsStrict() const
{
    return false;
}

// ****************************************************************************
//  Method:  GR1DRestartHDF5GeneralPluginInfo::OpensWholeDirectory
//
//  Purpose:
//    Returns if the GR1DRestartHDF5 plugin opens a whole directory name
//    instead of a single file.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
GR1DRestartHDF5GeneralPluginInfo::OpensWholeDirectory() const
{
    return false;
}
