// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <GR1DRestartHDF5PluginInfo.h>
#include <avtGR1DRestartHDF5FileFormat.h>
#include <avtMTMDFileFormatInterface.h>
#include <avtGenericDatabase.h>

// ****************************************************************************
//  Method:  GR1DRestartHDF5CommonPluginInfo::GetDatabaseType
//
//  Purpose:
//    Returns the type of a GR1DRestartHDF5 database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
DatabaseType
GR1DRestartHDF5CommonPluginInfo::GetDatabaseType()
{
    return DB_TYPE_MTMD;
}

// ****************************************************************************
//  Method: GR1DRestartHDF5CommonPluginInfo::SetupDatabase
//
//  Purpose:
//      Sets up a GR1DRestartHDF5 database.
//
//  Arguments:
//      list    A list of file names.
//      nList   The number of timesteps in list.
//      nBlocks The number of blocks in the list.
//
//  Returns:    A GR1DRestartHDF5 database from list.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabase *
GR1DRestartHDF5CommonPluginInfo::SetupDatabase(const char *const *list,
                                   int nList, int nBlock)
{
    (void)nList;
    (void)nBlock;
    avtMTMDFileFormat **ffl = new avtMTMDFileFormat*[1];
    ffl[0] = new avtGR1DRestartHDF5FileFormat(list[0]);
    avtMTMDFileFormatInterface *inter
           = new avtMTMDFileFormatInterface(ffl, 1);
    return new avtGenericDatabase(inter);
}
