// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <GR1DRestartHDF5PluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(GR1DRestartHDF5,Engine)

// ****************************************************************************
//  Method: GR1DRestartHDF5EnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a GR1DRestartHDF5 writer.
//
//  Returns:    A GR1DRestartHDF5 writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
GR1DRestartHDF5EnginePluginInfo::GetWriter(void)
{
    return NULL;
}

